esphomeyaml:
  name: sonoff_kitchen_hood
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout
  # FIXME without this the template switch is spamming
  esphomelib_version: dev
  on_boot:
    priority: 50
    then:
      - light.turn_on: led

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  hostname: sonoff-kitchen-hood
  domain: .lan

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_sonoff_username
  password: !secret mqtt_sonoff_password
  discovery_retain: true

logger:

ota:
  password: !secret ota_password

binary_sensor:
  - platform: status
    name: "Sonoff Kitchen Hood: Status"
  - platform: gpio
    name: "Sonoff Kitchen Hood: Button"
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_click:
      min_length: 50ms
      max_length: 350ms
      then:
        - switch.toggle: template_relay_1

switch:
  - platform: restart
    id: restart
    name: "Sonoff Kitchen Hood: Restart"
  - platform: gpio
    id: relay_1
    name: "Sonoff Kitchen Hood: Relay (w/o led)"
    pin: GPIO12
    internal: true
    inverted: true  # turn on relay on boot
  - platform: template
    id: template_relay_1
    name: "Sonoff Kitchen Hood: Relay"
    icon: "mdi:weather-windy"
    inverted: true  # because the underlying relay is inverted
    lambda: return id(relay_1).value;
    turn_on_action:
      then:
        - switch.turn_on: relay_1
        - light.turn_off: led  # NOTE: inverted
    turn_off_action:
      then:
        - switch.turn_off: relay_1
        - light.turn_on: led  # NOTE: inverted

output:
  - platform: esp8266_pwm
    id: basic_green_led
    pin:
      number: GPIO13
      inverted: true

light:
  - platform: monochromatic
    id: led
    name: "Sonoff Kitchen Hood: Green LED"
    output: basic_green_led
    default_transition_length: 0s
