esphomeyaml:
  name: sonoff_p0
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout
  # FIXME without this the template switch is spamming
  esphomelib_version: dev
  on_boot:
    priority: 50
    then:
      - switch.turn_on: template_relay_1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  hostname: sonoff-p0
  domain: .lan

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_sonoff_username
  password: !secret mqtt_sonoff_password
  discovery_retain: false

logger:

ota:
  password: !secret ota_password

binary_sensor:
  - platform: status
    name: "Sonoff p0: Status"
  - platform: gpio
    name: "Sonoff p0: Button"
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_click:
      min_length: 50ms
      max_length: 350ms
      then:
        - switch.toggle: template_relay_1

switch:
  - platform: restart
    id: restart
    name: "Sonoff p0: Restart"
  - platform: gpio
    id: relay_1
    name: "Sonoff p0: Relay (w/o led)"
    pin: GPIO12
    internal: true
  - platform: template
    id: template_relay_1
    name: "Sonoff p0: Relay"
    optimistic: true
    turn_on_action:
      then:
        - switch.turn_on: relay_1
        - light.turn_on: led
    turn_off_action:
      then:
        - switch.turn_off: relay_1
        - light.turn_off: led

output:
  - platform: esp8266_pwm
    id: basic_green_led
    inverted: true
    pin: GPIO13

light:
  - platform: monochromatic
    id: led
    name: "Sonoff p0: Green LED"
    output: basic_green_led
    default_transition_length: 0s
