esphomeyaml:
  name: sonoff_pow
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout
  # FIXME without this the template switch is spamming
  esphomelib_version: dev
  on_boot:
    priority: 50
    then:
      - light.turn_on: blue_led

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  hostname: sonoff-pow
  domain: .lan

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_sonoff_username
  password: !secret mqtt_sonoff_password
  discovery_retain: false

logger:

ota:
  password: !secret ota_password

binary_sensor:
  - platform: status
    name: "Sonoff POW: Status"
  - platform: gpio
    name: "Sonoff POW: Button"
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_click:
      - min_length: 50ms
        max_length: 350ms
        then:
          - switch.toggle: template_relay_1
      - min_length: 3000ms
        max_length: 6000ms
        then:
          - switch.toggle: restart

sensor:
  - platform: hlw8012
    sel_pin: 5
    cf_pin: 14
    cf1_pin: 13
    current:
      name: "Sonoff POW: HLW8012 Current"
      filters:
        - lambda: return fabs(x);
    voltage:
      name: "Sonoff POW: HLW8012 Voltage"
      filters:
        - lambda: return fabs(x);
    power:
      name: "Sonoff POW: HLW8012 Power"
      filters:
        - lambda: return fabs(x);
    update_interval: 2s

switch:
  - platform: restart
    id: restart
    name: "Sonoff POW: Restart"
  - platform: gpio
    id: relay_1
    name: "Sonoff POW: Relay (w/o led)"
    pin: GPIO12
    internal: true
    inverted: true  # turn on relay on boot
  - platform: template
    id: template_relay_1
    name: "Sonoff POW: Relay"
    inverted: true  # because the underlying relay is inverted
    lambda: return id(relay_1).value;
    turn_on_action:
      then:
        - switch.turn_on: relay_1
        - light.turn_off: blue_led  # NOTE: inverted
    turn_off_action:
      then:
        - switch.turn_off: relay_1
        - light.turn_on: blue_led  # NOTE: inverted

output:
  # https://community.home-assistant.io/t/esphomelib-a-comprehensive-solution-for-using-esps-with-home-assistant/55349/31
  - platform: gpio
    id: basic_blue_led
    pin: GPIO15

  # - platform: esp8266_pwm
  #   id: basic_green_led
  #   pin:
  #     number: GPIO13
  #     inverted: true

light:
  # - platform: monochromatic
  - platform: binary
    id: blue_led
    name: "Sonoff POW: Blue LED"
    # output: basic_green_led
    output: basic_blue_led
    # default_transition_length: 0s
