esphomeyaml:
  name: sonoff_bathroom_mirror_light
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout
  # FIXME without this the template switch is spamming
  esphomelib_version: dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: .lan
  hostname: sonoff-bathroom-mirror-light

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_sonoff_username
  password: !secret mqtt_sonoff_password

logger:

ota:
  password: !secret ota_password

binary_sensor:
  - platform: status
    name: "Sonoff Bathroom Mirror Light: Status"
  - platform: gpio
    name: "Sonoff Bathroom Mirror Light: Button"
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_click:
      min_length: 50ms
      max_length: 350ms
      then:
        - switch.toggle:
            id: template_relay_1

switch:
  - platform: restart
    id: restart
    name: "Sonoff Bathroom Mirror Light: Restart"
  - platform: gpio
    id: relay_1
    name: "Sonoff Bathroom Mirror Light: Relay (w/o led)"
    pin: GPIO12
    internal: true
    inverted: true  # turn on relay on boot
  - platform: template
    id: template_relay_1
    name: "Sonoff Bathroom Mirror Light: Relay"
    icon: "mdi:spotlight"
    inverted: true  # because the underlying relay is inverted
    # FIXME
    # This next code will spam the MQTT server
    # https://github.com/OttoWinter/esphomeyaml/issues/155
    # Once the next version (1.8.3?) is out this should work again
    lambda: return id(relay_1).value;
    # optimistic: true # FIXME delete this when the new version is available
    turn_on_action:
      then:
        - switch.turn_on:
            id: relay_1
        - light.turn_on:
            id: led
    turn_off_action:
      then:
        - switch.turn_off:
            id: relay_1
        - light.turn_off:
            id: led


output:
  - platform: esp8266_pwm
    id: basic_green_led
    pin:
      number: GPIO13
      inverted: false # turn on by default since the relay is on on boot

light:
  - platform: monochromatic
    id: led
    name: "Sonoff Bathroom Mirror Light: Green LED"
    output: basic_green_led
    default_transition_length: 0s
